services:
  - type: web
    name: feedsense-backend
    env: node
    plan: free
    branch: main
    repo: https://github.com/anandrajkcet09/Feed-Sense-Backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        scope: project
      - key: JWT_SECRET
        scope: project
      - key: ML_SERVICE_URL
        scope: project
      - key: CLIENT_URL
        scope: project
